### PR TITLE
fix: upgrade tamagui

### PR DESCRIPTION
**Pull request by RobSchilderr**

### CODE REVIEW

**Comment by RobSchilderr** [comment]
Also wondering if Expo can be updated to V50 @dohomi, as it causes issues, also in monorepos

**Comment by dohomi** [comment]
I have trouble running the tamagui upgrade path on my local machine.. I wonder why there is always a timeout

**Comment by RobSchilderr** [comment]
> I have trouble running the tamagui upgrade path on my local machine.. I wonder why there is always a timeout

Oh for me that was no issue, and in fact thats the only thing I did

**Comment by dohomi** [comment]
I published all packages to latest versions

**Pull request closed without merging**
